-- Reporting views + reporting_ro role — 2026-07-23
-- PAPER-TRAIL MIGRATION: launch/20_analytics-and-tracking/06_B3_reporting_views_admin_links.md
-- (Step 06) was executed directly against production Cloud SQL on 2026-07-22 without ever
-- committing the SQL to this repo. This file was generated by dumping the live definitions
-- and grants from production (pg_get_viewdef + information_schema.role_table_grants +
-- pg_class.relacl) — it is a record of what already exists, not a change to be deployed.
-- Running it against production again is a safe no-op: CREATE OR REPLACE VIEW and
-- GRANT are both idempotent, and the role block only creates reporting_ro if missing.
-- Run in Cloud SQL Studio: axis-and-bloom-prod → axisandbloom database.

-- ─── Role (create only if missing) ─────────────────────────────────────────────
-- reporting_ro already exists in production with LOGIN, no connection limit, no
-- password expiry, and is not a member of / doesn't grant membership to any other
-- role. Its actual password lives outside this file (Secret Manager per the Step 06
-- spec's own instruction) — set/rotate it separately with
-- ALTER ROLE reporting_ro WITH PASSWORD '<from Secret Manager>'; never commit it here.

DO $$ BEGIN
  CREATE ROLE reporting_ro WITH LOGIN;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT CONNECT ON DATABASE axisandbloom TO reporting_ro;
GRANT USAGE ON SCHEMA public TO reporting_ro;

-- ─── Views ──────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW public.v_subscribers_weekly AS
 SELECT date_trunc('week'::text, ns.created_at)::date AS week,
    COALESCE(ss.label, 'Unknown'::text) AS source,
    count(*) AS new_subscribers
   FROM newsletter_subscriber ns
     LEFT JOIN subscriber_source ss ON ss.id = ns.source_id
  GROUP BY (date_trunc('week'::text, ns.created_at)::date), (COALESCE(ss.label, 'Unknown'::text))
  ORDER BY (date_trunc('week'::text, ns.created_at)::date) DESC, (COALESCE(ss.label, 'Unknown'::text));

CREATE OR REPLACE VIEW public.v_quiz_funnel_weekly AS
 SELECT date_trunc('week'::text, quiz_funnel_event.created_at)::date AS week,
    count(*) FILTER (WHERE quiz_funnel_event.event = 'quiz_start'::text) AS starts,
    count(*) FILTER (WHERE quiz_funnel_event.event = 'quiz_complete'::text) AS completes,
    count(*) FILTER (WHERE quiz_funnel_event.event = 'email_submitted'::text) AS emails_submitted,
    round(count(*) FILTER (WHERE quiz_funnel_event.event = 'quiz_complete'::text)::numeric / NULLIF(count(*) FILTER (WHERE quiz_funnel_event.event = 'quiz_start'::text), 0)::numeric * 100::numeric, 1) AS completion_rate,
    round(count(*) FILTER (WHERE quiz_funnel_event.event = 'email_submitted'::text)::numeric / NULLIF(count(*) FILTER (WHERE quiz_funnel_event.event = 'quiz_complete'::text), 0)::numeric * 100::numeric, 1) AS optin_rate
   FROM quiz_funnel_event
  GROUP BY (date_trunc('week'::text, quiz_funnel_event.created_at)::date)
  ORDER BY (date_trunc('week'::text, quiz_funnel_event.created_at)::date) DESC;

CREATE OR REPLACE VIEW public.v_archetype_distribution AS
 SELECT newsletter_subscriber.archetype,
    count(*) AS subscriber_count,
    round(count(*)::numeric / NULLIF(sum(count(*)) OVER (), 0::numeric) * 100::numeric, 1) AS share
   FROM newsletter_subscriber
  WHERE newsletter_subscriber.archetype IS NOT NULL
  GROUP BY newsletter_subscriber.archetype
  ORDER BY (count(*)) DESC;

CREATE OR REPLACE VIEW public.v_orders_weekly AS
 WITH first_orders AS (
         SELECT "order".user_id,
            min("order".created_at) AS first_order_at
           FROM "order"
          WHERE "order".user_id IS NOT NULL
          GROUP BY "order".user_id
        )
 SELECT date_trunc('week'::text, o.created_at)::date AS week,
    count(*) AS orders,
    count(DISTINCT fo.user_id) FILTER (WHERE date_trunc('week'::text, fo.first_order_at) = date_trunc('week'::text, o.created_at)) AS new_customers,
    round(sum(o.total_amount_paid) * 100::numeric)::bigint AS revenue_cents
   FROM "order" o
     LEFT JOIN first_orders fo ON fo.user_id = o.user_id
  GROUP BY (date_trunc('week'::text, o.created_at)::date)
  ORDER BY (date_trunc('week'::text, o.created_at)::date) DESC;

-- ─── Grants — SELECT on these four views only, nothing else ────────────────────
-- Confirmed against production: information_schema.role_table_grants for grantee
-- reporting_ro returns exactly these 4 rows (all SELECT, no base tables, no other
-- views); pg_class.relacl on each view is exactly "{owner=arwdDxt/owner,reporting_ro=r/owner}".

GRANT SELECT ON public.v_subscribers_weekly TO reporting_ro;
GRANT SELECT ON public.v_quiz_funnel_weekly TO reporting_ro;
GRANT SELECT ON public.v_archetype_distribution TO reporting_ro;
GRANT SELECT ON public.v_orders_weekly TO reporting_ro;

-- ─── Verify ───────────────────────────────────────────────────────────────────

SELECT table_name, privilege_type
FROM information_schema.role_table_grants
WHERE grantee = 'reporting_ro'
ORDER BY table_name, privilege_type;
